travis:
  secure:
    BINSTAR_TOKEN: Z6Rg7ymsV7ro7kC5Dzq6yRNcLkVJFgp1KlVEVCb1pCDYvd/htUKjGtMeq9UYeqjionfWAMudsSvr32HiCjzabSE7FN+I6QiORScIppYtk76E2V83ks+uMg/gOpi/N5OfG3vdZFUI7qUTokEnOXm9UrSh4RT4Mm/HqwdV3zoPXuqczSD/fYa8rggfcypRISExnEOzglt3+D2mb5MgkJMarmNAzBJoI5EaLlSpTzzULY3itYGDarJ5z4MAQcctfoSQOCIxxAR8ua289WKwVkXfRwObgbxL4KG8eb3cN7Eg0yb+kVW6jjr6swsf4HhjCEhRDmnBisaILsUkeKZwMTDMcFubErse/izNgxx5f6Lgo8h2AzLFFnDKRRA7a1plt1qczCLAO5ThghRNO9MEk70lojbRUd37JGWW7WAj+sNXs9xqnfpVXZQcjuJT61kwPr/7RHSAR9avCWyh8Ny3L5XwtOixsl2Hgi8c2NlguM9gJ+jL84p/0HcD+d6NkBQpP389pydc5TncgIojnQB+05j70S5ymh+IVxZdROkQXo9VtmEtDkHwoYnJYm780RpRKSV9HvZqJKmcZI0vPR19o1F7bF1amgA+WEMWjHj6bbAIuSLF+E5vb3wSniDEu7VgEYNZxczEkgG2t7E1blxw7XvWIxfixpvbcyknnuC6w6kh1Fc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
